### ISSUE TITLE
'memset' not declared on Ubuntu

### ISSUE THREAD

**Issue by semmel** [uskr/jsonrpc-lean#3]
Nice library :cake: 
When compiling with GCC C++14 flavour on Linux I had to make a small change in `util.h` in line 24
```cpp
#include <string.h>
``` 
Apparently `memset` is part of `<string.h>` and not STL's `<string>`.
See also on [Stackoverflow](http://stackoverflow.com/questions/26832672/error-memset-was-not-declared-in-this-scope) this answer:

> You should use #include <string.h> in both C and C++, if you want to use ::memset. #include <cstring> gets you std::memset, and if it also makes ::memset available, it does so by accident. The Standard permits it but does not require it to do so

Right now I have not time to compile on Mac and Windows, therefore I did not assemble a pull request though.

**Comment by uskr** [comment]
Thank you for the feedback. I will test it and fix.

**Comment by uskr** [comment]
Tested and fixed.
