### ISSUE TITLE
uint32_t and uint64_t types

### ISSUE THREAD

**Issue by jbp9** [uskr/jsonrpc-lean#4]
Is there a reason why uint32_t and uint64_t are omitted from Value type? I see they are being converted to int64_t and double receptively.  The problem is I'm unable to 'AddMethod' following : 

uint32_t foo() {}

Thank you,
J

**Comment by uskr** [comment]
For simplicity, the lib supports DOUBLE, INTEGER_32 and INTEGER_64, using double, int32_t and int64_t, respectively. Which all maps nicely to JSON.

Since JSON only supports "integer" and "number" types, it doesn't make sense to have a "unsigned" setter/getter.

**Comment by jbp9** [comment]
Fair enough, I've modified code for my usage. But current code, will not allow to "AddMethod" with unsigned return and also params I think (which I think is arbitrary limitation).
