### ISSUE TITLE
LGPL version 2.1 contradiction

### ISSUE THREAD

**Issue by 0ss0** [uskr/jsonrpc-lean#6]
Hello,
nice approach, but not really useful.

Since you advertise you library as header only, then I would suggest to change license LGPL v2.1 to LGPL v3.0. Because LGPL v2.1 requires to link library dynamically, which is problematic with headers only libraries and is solved in LGPL v3.0, as stated here:
http://eigen.tuxfamily.org/index.php?title=Licensing_FAQ&oldid=1117#But_doesn.27t_the_LGPL_have_issues_with_code_that_is_in_header_files.2C_and_template_libraries.3F

**Comment by uskr** [comment]
Good point. Will fix this in a couple days. Thank you.

**Comment by uskr** [comment]
Done. Updated to LGPL v3.0.

The individual files already mentioned 2.1 or newer available. But I updated all of them and the LICENSE file for clarity.

Thank you for the feedback.

**Comment by 0ss0** [comment]
Great, thanks, now we have one option more to consider ;)
